import type { Building, ConveyorBelt, Worker, WorkerType, WorkerTypeConfig, AlertEvent } from "./types";

// ─── WORKER TYPE CONFIG ─────────────────────────────────────────────────────

export const WORKER_TYPE_CONFIG: Record<WorkerType, WorkerTypeConfig> = {
  builder:   { color: "#06b6d4", icon: "H", shape: "square",   trailColor: "#06b6d4", label: "Builder" },
  inspector: { color: "#eab308", icon: "Q", shape: "diamond",  trailColor: "#eab308", label: "Inspector" },
  miner:     { color: "#22c55e", icon: "P", shape: "circle",   trailColor: "#22c55e", label: "Miner" },
  scout:     { color: "#a855f7", icon: "W", shape: "triangle", trailColor: "#a855f7", label: "Scout" },
  deployer:  { color: "#f97316", icon: "R", shape: "hexagon",  trailColor: "#f97316", label: "Deployer" },
  messenger: { color: "#3b82f6", icon: "Z", shape: "bolt",     trailColor: "#3b82f6", label: "Messenger" },
  browser:   { color: "#0ea5e9", icon: "G", shape: "dodecahedron", trailColor: "#0ea5e9", label: "Browser" },
};

// ─── DATA TYPE COLORS ───────────────────────────────────────────────────────

export const DATA_TYPE_COLORS: Record<string, string> = {
  code:    "#3b82f6",
  tests:   "#22c55e",
  revenue: "#eab308",
  errors:  "#ef4444",
  config:  "#06b6d4",
  data:    "#a855f7",
  deploy:  "#f97316",
  alerts:  "#e8a019",
};

// ─── BUILDINGS ──────────────────────────────────────────────────────────────

export const BUILDINGS: Building[] = [
  {
    id: "command-center",
    name: "Command Center",
    shortName: "CMD",
    color: "#e8a019",
    glowColor: "rgba(232, 160, 25, 0.4)",
    topColor: "#f5c842",
    leftColor: "#c4870f",
    rightColor: "#9a6a08",
    size: 3,
    gridX: 5,
    gridY: 5,
    status: "active",
    description: "ClawBot / Admin Dashboard -- Central AI orchestration hub",
    stats: { tests: 142, deploys: 38, uptime: "99.7%" },
  },
  {
    id: "buildkit",
    name: "BuildKit Services HQ",
    shortName: "BK",
    color: "#06b6d4",
    glowColor: "rgba(6, 182, 212, 0.4)",
    topColor: "#22d3ee",
    leftColor: "#0891b2",
    rightColor: "#0e7490",
    size: 2,
    gridX: 9,
    gridY: 2,
    status: "active",
    description: "Infrastructure hub -- DNS, deployments, monitoring",
    stats: { tests: 56, deploys: 24, uptime: "99.9%" },
  },
  {
    id: "email-finder",
    name: "Email Finder Lab",
    shortName: "EML",
    color: "#8b5cf6",
    glowColor: "rgba(139, 92, 246, 0.4)",
    topColor: "#a78bfa",
    leftColor: "#7c3aed",
    rightColor: "#6d28d9",
    size: 1.5,
    gridX: 2,
    gridY: 8,
    status: "idle",
    description: "Lead enrichment -- Email discovery and validation",
    stats: { tests: 34, deploys: 12, uptime: "97.5%" },
  },
  {
    id: "barrelhouse",
    name: "BarrelHouse CRM",
    shortName: "BH",
    color: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.4)",
    topColor: "#fbbf24",
    leftColor: "#d97706",
    rightColor: "#b45309",
    size: 2,
    gridX: 8,
    gridY: 8,
    status: "active",
    description: "Franchise CRM -- Phase 2 complete, client demo ready",
    stats: { tests: 178, deploys: 45, uptime: "99.1%" },
  },
  {
    id: "pc-bottleneck",
    name: "PC Bottleneck Factory",
    shortName: "PCB",
    color: "#f97316",
    glowColor: "rgba(249, 115, 22, 0.4)",
    topColor: "#fb923c",
    leftColor: "#ea580c",
    rightColor: "#c2410c",
    size: 2,
    gridX: 12,
    gridY: 5,
    status: "active",
    description: "Flagship product -- pcbottleneck.buildkit.store, Amazon affiliate",
    stats: { tests: 203, deploys: 52, uptime: "99.8%" },
  },
  {
    id: "outdoor-crm",
    name: "Outdoor CRM Barracks",
    shortName: "OCR",
    color: "#22c55e",
    glowColor: "rgba(34, 197, 94, 0.4)",
    topColor: "#4ade80",
    leftColor: "#16a34a",
    rightColor: "#15803d",
    size: 1.5,
    gridX: 0,
    gridY: 5,
    status: "idle",
    description: "AATOS Outdoor CRM -- React + Django, proposal sent",
    stats: { tests: 267, deploys: 31, uptime: "99.4%" },
  },
  {
    id: "chess-academy",
    name: "Chess Academy",
    shortName: "CHE",
    color: "#14b8a6",
    glowColor: "rgba(20, 184, 166, 0.4)",
    topColor: "#2dd4bf",
    leftColor: "#0d9488",
    rightColor: "#0f766e",
    size: 1.5,
    gridX: 5,
    gridY: 1,
    status: "idle",
    description: "AI Chess Coach -- Lichess integration, analysis engine",
    stats: { tests: 45, deploys: 8, uptime: "99.0%" },
  },
  {
    id: "finance-brief",
    name: "Finance Brief Tower",
    shortName: "FIN",
    color: "#10b981",
    glowColor: "rgba(16, 185, 129, 0.4)",
    topColor: "#34d399",
    leftColor: "#059669",
    rightColor: "#047857",
    size: 2,
    gridX: 11,
    gridY: 1,
    status: "active",
    description: "AI Finance Brief -- Daily market digest, SEO autopilot",
    stats: { tests: 78, deploys: 41, uptime: "99.6%" },
  },
  {
    id: "automation-hub",
    name: "Automation Hub",
    shortName: "N8N",
    color: "#a855f7",
    glowColor: "rgba(168, 85, 247, 0.4)",
    topColor: "#c084fc",
    leftColor: "#9333ea",
    rightColor: "#7e22ce",
    size: 2,
    gridX: 3,
    gridY: 10,
    status: "active",
    description: "n8n workflow hub -- 6 active workflows, Railway hosted",
    stats: { tests: 12, deploys: 19, uptime: "98.8%" },
  },
  {
    id: "pl-engine",
    name: "PL Engine Forge",
    shortName: "PLE",
    color: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.4)",
    topColor: "#f87171",
    leftColor: "#dc2626",
    rightColor: "#b91c1c",
    size: 1.5,
    gridX: 7,
    gridY: 11,
    status: "warning",
    description: "P&L Engine -- Archived, data still accessible",
    stats: { tests: 156, deploys: 28, uptime: "0%" },
  },
  {
    id: "mcp-array",
    name: "MCP Server Array",
    shortName: "MCP",
    color: "#e2e8f0",
    glowColor: "rgba(226, 232, 240, 0.3)",
    topColor: "#f1f5f9",
    leftColor: "#cbd5e1",
    rightColor: "#94a3b8",
    size: 1.5,
    gridX: 12,
    gridY: 9,
    status: "active",
    description: "MCP server infrastructure -- 12 servers configured",
    stats: { tests: 0, deploys: 12, uptime: "99.5%" },
  },
];

// ─── CONVEYORS ──────────────────────────────────────────────────────────────

export const CONVEYORS: ConveyorBelt[] = [
  { id: "c2", fromBuildingId: "command-center", toBuildingId: "buildkit", color: "#06b6d4", dataType: "config", active: true, throughput: 18 },
  { id: "c4", fromBuildingId: "automation-hub", toBuildingId: "command-center", color: "#e8a019", dataType: "alerts", active: true, throughput: 8 },
  { id: "c5", fromBuildingId: "pc-bottleneck", toBuildingId: "finance-brief", color: "#eab308", dataType: "revenue", active: true, throughput: 15 },
  { id: "c6", fromBuildingId: "buildkit", toBuildingId: "barrelhouse", color: "#f59e0b", dataType: "deploy", active: true, throughput: 6 },
  { id: "c7", fromBuildingId: "barrelhouse", toBuildingId: "pc-bottleneck", color: "#22c55e", dataType: "tests", active: false, throughput: 0 },
  { id: "c8", fromBuildingId: "command-center", toBuildingId: "chess-academy", color: "#14b8a6", dataType: "code", active: false, throughput: 0 },
  { id: "c9", fromBuildingId: "finance-brief", toBuildingId: "automation-hub", color: "#a855f7", dataType: "data", active: true, throughput: 31 },
  { id: "c10", fromBuildingId: "mcp-array", toBuildingId: "command-center", color: "#e2e8f0", dataType: "config", active: true, throughput: 12 },
];

// ─── WORKERS ────────────────────────────────────────────────────────────────

export const INITIAL_WORKERS: Worker[] = [
  {
    id: "w1",
    name: "Hammerhead",
    type: "builder",
    color: "#06b6d4",
    level: 5,
    xp: 47,
    currentBuildingId: "command-center",
    targetBuildingId: "buildkit",
    task: "Building infrastructure update",
    progress: 65,
    speechBubble: null,
    status: "moving",
    evolving: false,
  },
  {
    id: "w2",
    name: "Lens",
    type: "inspector",
    color: "#eab308",
    level: 3,
    xp: 28,
    currentBuildingId: "barrelhouse",
    targetBuildingId: "automation-hub",
    task: "Auditing CRM data pipeline",
    progress: 30,
    speechBubble: null,
    status: "working",
    evolving: false,
  },
  {
    id: "w3",
    name: "Digger",
    type: "miner",
    color: "#22c55e",
    level: 7,
    xp: 63,
    currentBuildingId: "pc-bottleneck",
    targetBuildingId: "finance-brief",
    task: "Mining SEO keyword data",
    progress: 82,
    speechBubble: null,
    status: "moving",
    evolving: false,
  },
  {
    id: "w4",
    name: "Windrider",
    type: "scout",
    color: "#a855f7",
    level: 2,
    xp: 15,
    currentBuildingId: "barrelhouse",
    targetBuildingId: "buildkit",
    task: "Scouting CRM Phase 3 features",
    progress: 45,
    speechBubble: null,
    status: "working",
    evolving: false,
  },
  {
    id: "w5",
    name: "Igniter",
    type: "deployer",
    color: "#f97316",
    level: 4,
    xp: 38,
    currentBuildingId: "automation-hub",
    targetBuildingId: "command-center",
    task: "Deploying health check sweep",
    progress: 90,
    speechBubble: null,
    status: "moving",
    evolving: false,
  },
  {
    id: "w6",
    name: "Sparky",
    type: "messenger",
    color: "#3b82f6",
    level: 6,
    xp: 55,
    currentBuildingId: "command-center",
    targetBuildingId: "barrelhouse",
    task: "Sending deploy notifications",
    progress: 20,
    speechBubble: null,
    status: "moving",
    evolving: false,
  },
];

// ─── SPEECH BUBBLES ─────────────────────────────────────────────────────────

export const SPEECH_BUBBLES = [
  "Mining data...",
  "PR ready!",
  "Job's done!",
  "Build passing...",
  "Deploying...",
  "Tests green!",
  "Scanning domain...",
  "Found an email!",
  "Refactoring...",
  "Crunching numbers...",
  "Optimizing...",
  "Pipeline complete!",
  "Workflow triggered!",
];

// ─── EVENTS ─────────────────────────────────────────────────────────────────

export const INITIAL_EVENTS: AlertEvent[] = [
  { id: "e2", time: "14:31:45", message: "Autopilot SEO: Published 'Best GPUs for AI Training 2026'", type: "info" },
  { id: "e3", time: "14:30:12", message: "BarrelHouse CRM: Phase 2 deploy successful", type: "success" },
  { id: "e4", time: "14:28:55", message: "n8n Workflow: Daily P&L digest sent to Discord", type: "info" },
  { id: "e5", time: "14:27:30", message: "PL Engine: Service archived -- no heartbeat", type: "warning" },
  { id: "e6", time: "14:25:01", message: "PC Bottleneck: 12 new Amazon clicks today", type: "success" },
  { id: "e7", time: "14:22:18", message: "Health Check: All 6 services responding", type: "info" },
  { id: "e8", time: "14:20:00", message: "Finance Brief: Market brief delivered -- 3 recipients", type: "success" },
];

export const NEW_EVENT_MESSAGES = [
  { message: "Worker Hammerhead completed build task", type: "success" as const },
  { message: "Autopilot: New blog post queued for review", type: "info" as const },
  { message: "MCP Array: 12 servers healthy, 0 degraded", type: "success" as const },
  { message: "Chess Academy: Lichess API rate limit warning", type: "warning" as const },
  { message: "BuildKit: SSL certificate renewed for buildkit.store", type: "success" as const },
  { message: "n8n: Automation workflow completed", type: "info" as const },
];
